//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
		public class LinearFunction:IFunction
		{

		private float A;

		private float B;

		public LinearFunction (float a,float b)
				{
			this.A = a;
			this.B = b;
				}
		#region implemented abstract members of IFunction

		public override void DrawGraph ()
		{

		}

		private float calcFunc(float x)
		{
			return A * x + B;
		}

		public override bool IsHit (Vector2 player)
		{
			return calcFunc (player.x) == player.y;
		}

		public override string functionName {
			get {
				return "LinearFunction";
			}
		}

		public override int functionLevel {
			get {
				return 1;
			}
		}

		#endregion


		}
}

