//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets.Scripts.Functions.PrefabController;
using Functions.PrefabController;
using UnityEditor;
using UnityEngine;
using Random = UnityEngine.Random;


namespace AssemblyCSharp
{
		public class TailerSinFunction:IFunction
		{

            

		private float A;

		private float B;

		private float C;

		    private float D;

		    private bool IsNegative;

		public TailerSinFunction ()
				{
				}
		#region implemented abstract members of IFunction

		    public override void Refresh()
		    {
		        A = 1;
		        B =0 ;
				C = Random.Range(1, 4)*(Random.Range (0,1)*2-1);
				D = Random.Range(1, 9)*(Random.Range (0,1)*2-1);
				IsNegative = Random.Range (0,1) != 0 ? true : false;
		    }

		    public override void DrawGraph (float time)
		{

		}

		    public override void BeginDraw(GameManager gameManager)
		    {
		        var gameObject = FunctionPrefabContainer.instance.SinGameObject;
                var controller = gameObject.GetComponent<SinFunctionController>();
                controller.A = A;
                controller.C = C;
                controller.B = B;
		        controller.D = D;
		        controller.IsNegative = IsNegative;
		        gameManager.BasicGraphTarget.ChangeGameObject(gameObject);

		    }

		    private float calcFunc(float x)
		    {
		        return (float) (D*Math.Sin(x*A + B) + C);
		    }

            public override bool IsHit(Vector2 player)
            {
                if (IsNegative)
                {
                    return calcFunc(player.x) > player.y;
                }
                else
                {
                    return calcFunc(player.x) < player.y;
                }
            }

		public override string functionName {
			get {
				return "LinearFunction";
			}
		}

		public override int functionLevel {
			get {
				return 1;
			}
		}

		    public override float waitingTimeInSecound
		    {
		        get { return 3; }
		    }

		    public override void DrawFormula(GameManager gameManager)
		    {
		        gameManager.BasicFormulaTarget.text = string.Format("y");
		        gameManager.BasicFormulaTarget.text += IsNegative ? string.Format("<") : string.Format(">");
		        gameManager.BasicFormulaTarget.text += string.Format("lim(n->∞){0}*∑(k=1,n)((-1)^(n+1))/(2n-1)!*x^(2n-1)+{1}",
		            A, B);

		        #endregion

		    }
		}
}

